default:
  image: klakegg/hugo:busybox

stages:
  - build
  - deploy

build:
  stage: build
  image: klakegg/hugo:busybox
  script:
    - hugo
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  image: alpine:latest
  script:
    - find public -type f -iregex '.*\.\(html\|js\|css\|svg\|webmanifest\|fnt\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
      - public
  only:
    - master
