baseURL = 'https://getkey.eu/'
title = 'Julien Mourer'

[markup]
  [markup.highlight]
    style = 'onedark'

[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-atom-feed"

[outputs]
  section = ["HTML", "RSS", "ATOM"]
