baseURL = 'https://mourer.eu/'
title = 'Julien Mourer'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.highlight]
    style = 'onedark'
  [markup.goldmark.renderer]
    hardWraps = true
    unsafe = true

[outputs]
  section = ["HTML", "RSS"]
