version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
  web:
    build: .
    ports:
      - "8083:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo/blog
